In [1]:
import pandas as pd
import glob
import os
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# Create a loop to join 250K multiple of wine enthusiast mag 

master_df = pd.DataFrame()

for file in os.listdir(os.getcwd()):
    if file.endswith('.csv'): 
        master_df = master_df.append(pd.read_csv(file))

In [3]:
master_df.to_csv('Master_wine.csv', index=False)

In [4]:
master_df

,alcohol,category,country,description,designation,price,rating,region,subregion,subsubregion,title,url,varietal,vintage,winery
0,14.0,Red,Spain,"Seductive like a trap, meaning the nose is lus...",NaN,36.0,87,Northern Spain,Ribera del Duero,NaN,Arrocal 2004 Ribera del Duero,https://www.winemag.com/buying-guide/arrocal-2...,Tempranillo,2004.0,Arrocal
1,14.8,Red,US,The vineyard is on Atlas Peak. Modern winemaki...,Mountainside Vineyards,50.0,87,California,Napa,Napa Valley,Erba 2003 Mountainside Vineyards Cabernet Sauv...,https://www.winemag.com/buying-guide/erba-2003...,Cabernet Sauvignon,2003.0,Erba
2,NaN,Red,US,"Has true varietal spice, something we don't al...",Limited Release Stepmaker's,14.0,87,California,Central Coast,Central Coast,Concannon 2004 Limited Release Stepmaker's Syr...,https://www.winemag.com/buying-guide/concannon...,Syrah,2004.0,Concannon
3,13.5,Red,Spain,is a nice wine that's at peak maturity. The no...,Reserva,26.0,87,Northern Spain,Ribera del Duero,NaN,San Gabriel 2001 Reserva (Ribera del Duero),https://www.winemag.com/buying-guide/san-gabri...,Tempranillo,2001.0,San Gabriel
4,14.5,Red,Spain,"Alongside open, hefty berry aromas are bramble...",Vendimia Seleccionada,21.0,87,Northern Spain,Ribera del Duero,NaN,Casajús 2005 Vendimia Seleccionada (Ribera de...,https://www.winemag.com/buying-guide/casajus-2...,Tempranillo,2005.0,Casajús
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14933,13.0,White,France,"Rich and creamy, this is a delicious, ripe, an...",Domaine de la Charmoise,15.0,89,Loire Valley,Touraine,NaN,Henry Marionnet 2016 Domaine de la Charmoise S...,https://www.winemag.com/buying-guide/henry-mar...,Sauvignon Blanc,2016.0,Henry Marionnet
14934,12.0,Sparkling,France,"Pale, almost Provence rosé in color, this frui...",Brut Rosé,45.0,89,Champagne,Champagne,NaN,Henri Abelé NV Brut Rosé (Champagne),https://www.winemag.com/buying-guide/henri-abe...,Champagne Blend,NaN,Henri Abelé
14935,11.0,Sparkling,Italy,"Silky and fresh, this bright sparkler delivers...",Rustico Brut,19.0,89,Veneto,Valdobbiadene Prosecco Superiore,NaN,Nino Franco NV Rustico Brut (Valdobbiadene Pr...,https://www.winemag.com/buying-guide/nino-fran...,Glera,NaN,Nino Franco
14936,12.0,Sparkling,France,Drier than it used to be—and better for it—thi...,Rosé Impérial,50.0,89,Champagne,Champagne,NaN,Moët &amp; Chandon NV Rosé Impérial (Champagne),https://www.winemag.com/buying-guide/moet-chan...,Champagne Blend,NaN,Moët &amp; Chandon
14937,13.6,Red,US,"The vineyard lies in the Van Duzer corridor, a...",Havlin Vineyard,35.0,89,Oregon,Willamette Valley,Willamette Valley,Martin Woods 2016 Havlin Vineyard Gamay (Willa...,https://www.winemag.com/buying-guide/martin-wo...,Gamay,2016.0,Martin Woods

In [5]:
#drop colummns 

master_df = master_df.drop(['description', 'designation','subregion',"subsubregion","title",'url','winery'], axis = 1)

In [6]:
master_df

,alcohol,category,country,price,rating,region,varietal,vintage
0,14.0,Red,Spain,36.0,87,Northern Spain,Tempranillo,2004.0
1,14.8,Red,US,50.0,87,California,Cabernet Sauvignon,2003.0
2,NaN,Red,US,14.0,87,California,Syrah,2004.0
3,13.5,Red,Spain,26.0,87,Northern Spain,Tempranillo,2001.0
4,14.5,Red,Spain,21.0,87,Northern Spain,Tempranillo,2005.0
...,...,...,...,...,...,...,...,...
14933,13.0,White,France,15.0,89,Loire Valley,Sauvignon Blanc,2016.0
14934,12.0,Sparkling,France,45.0,89,Champagne,Champagne Blend,NaN
14935,11.0,Sparkling,Italy,19.0,89,Veneto,Glera,NaN
14936,12.0,Sparkling,France,50.0,89,Champagne,Champagne Blend,NaN
14937,13.6,Red,US,35.0,89,Oregon,Gamay,2016.0

In [7]:
#Filter by Country // We only need Portugal

master_df = master_df.query("country == 'Portugal'")

In [8]:
master_df

,alcohol,category,country,price,rating,region,varietal,vintage
1419,20.0,Port/Sherry,Portugal,27.0,83,Douro,Port,NaN
1573,NaN,Red,Portugal,15.0,91,Dão,Portuguese Red,2003.0
1619,NaN,Red,Portugal,NaN,91,Douro,Portuguese Red,2001.0
1630,14.5,Red,Portugal,58.0,91,Alentejano,Portuguese Red,2003.0
1651,14.5,Red,Portugal,90.0,92,Alentejano,Portuguese Red,2004.0
...,...,...,...,...,...,...,...,...
13796,12.5,Rose,Portugal,9.0,84,Vinho Verde,Rosé,2016.0
13808,13.0,Red,Portugal,18.0,84,Lisboa,Portuguese Red,2016.0
13810,14.0,Red,Portugal,NaN,84,Península de Setúbal,Portuguese Red,2016.0
13811,9.5,White,Portugal,8.0,84,Vinho Verde,Portuguese White,NaN
13814,12.5,Sparkling,Portugal,16.0,85,Bairrada,Portuguese Sparkling,2015.0

In [9]:
master_df = master_df.query("category == 'White'")

In [10]:
master_df

,alcohol,category,country,price,rating,region,varietal,vintage
2113,13.5,White,Portugal,18.0,85,Douro,Arinto,2004.0
2157,NaN,White,Portugal,NaN,86,Ribatejano,Portuguese White,2005.0
5535,12.5,White,Portugal,13.0,89,Alentejo,Portuguese White,2005.0
5653,14.0,White,Portugal,12.0,90,Douro,White Blend,2005.0
5884,11.0,White,Portugal,14.0,86,Terras do Sado,Muscat,2004.0
...,...,...,...,...,...,...,...,...
13735,12.0,White,Portugal,10.0,83,Tejo,Fernão Pires,2016.0
13739,12.5,White,Portugal,10.0,83,Minho,Fernão Pires,2016.0
13753,12.0,White,Portugal,18.0,84,Lisboa,Portuguese White,2016.0
13767,24.0,White,Portugal,12.0,84,Douro,Portuguese White,2016.0
13811,9.5,White,Portugal,8.0,84,Vinho Verde,Portuguese White,NaN

In [11]:
#drop NA values for alcohol & rating

white_winedf = master_df.dropna(subset=['alcohol', 'rating', 'price'])

In [12]:

white_winedf

,alcohol,category,country,price,rating,region,varietal,vintage
2113,13.5,White,Portugal,18.0,85,Douro,Arinto,2004.0
5535,12.5,White,Portugal,13.0,89,Alentejo,Portuguese White,2005.0
5653,14.0,White,Portugal,12.0,90,Douro,White Blend,2005.0
5884,11.0,White,Portugal,14.0,86,Terras do Sado,Muscat,2004.0
6103,13.0,White,Portugal,12.0,86,Estremadura,Arinto,2005.0
...,...,...,...,...,...,...,...,...
13735,12.0,White,Portugal,10.0,83,Tejo,Fernão Pires,2016.0
13739,12.5,White,Portugal,10.0,83,Minho,Fernão Pires,2016.0
13753,12.0,White,Portugal,18.0,84,Lisboa,Portuguese White,2016.0
13767,24.0,White,Portugal,12.0,84,Douro,Portuguese White,2016.0
13811,9.5,White,Portugal,8.0,84,Vinho Verde,Portuguese White,NaN

In [13]:
#Row 13767 has a incorrect value // wines never reach that kind of %ABV

white_winedf = white_winedf.drop(index=13767)
white_winedf['alcohol'].describe()

count    6253.000000
mean       12.601631
std         1.009536
min         8.500000
25%        12.500000
50%        13.000000
75%        13.000000
max        24.000000
Name: alcohol, dtype: float64

In [14]:
white_winedf['rating'].describe()

count    6253.000000
mean       87.377579
std         2.386366
min        81.000000
25%        85.000000
50%        87.000000
75%        89.000000
max        95.000000
Name: rating, dtype: float64

In [15]:
white_winedf['price'].describe()

count    6253.000000
mean       16.711818
std        10.105258
min         5.000000
25%        10.000000
50%        14.000000
75%        20.000000
max        95.000000
Name: price, dtype: float64

In [16]:
white_winedf.to_csv('Portuguesewhites.csv', index=False)